# Generated by Django 4.2.2 on 2023-07-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='boc_id',
            field=models.CharField(blank=True, default='000000', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user_bvpgnf.png', upload_to='profiles/'),
        ),
    ]
