# Generated by Django 4.2.2 on 2023-07-05 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_profile_boc_id_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='boc_id',
        ),
    ]
